services:
  migrol-bot:
    build: .
    container_name: migrol-bot
    environment:
      CLIENT_SECRET: "${CLIENT_SECRET}"
      APP_INSTALLATION_ID: "${APP_INSTALLATION_ID}"
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      TELEGRAM_CHAT_ID: "${TELEGRAM_CHAT_ID}"
    volumes:
      - ./coupons:/app/coupons
    restart: unless-stopped
